### ISSUE TITLE
Create Model USER - USER_IS_USER_TYPE

### ISSUE THREAD

**Issue by ekpo-d** [mykeels/college-portal#7]
As a User
I want to be of a particular type
In order to have specific roles.

##### Required Fields
USERS_ID, 
USER_TYPE_ID

##### Model Dependencies
USERS,
USER_TYPE

##### Notes:
![image](https://user-images.githubusercontent.com/11996508/32836634-ca499a66-ca0a-11e7-91ed-19f5b42b4c7c.png)

**Comment by mykeels** [comment]
![image](https://user-images.githubusercontent.com/11996508/32836634-ca499a66-ca0a-11e7-91ed-19f5b42b4c7c.png)
